version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - app-db:/var/lib/postgresql/data

  app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '3000:3000'
        
volumes:
  app-db: